website/ws2.0/server/app/contact/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, SubmitField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from wtforms.widgets.core import TextArea
from ..models import User

class ContactForm(FlaskForm):
    firstname = StringField('First Name', validators=[DataRequired()])
    lastname = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Length(1, 64), Email()])
    phonenumber= StringField('Phone Number', validators=[DataRequired()])
    subject= StringField('Message Subject', validators=[DataRequired()])
    message= TextAreaField('Tell us about your question', validators=[DataRequired()])
    email_message = BooleanField('Email', validators=[DataRequired()])
    phone_message = BooleanField('Phone', validators=[DataRequired()])
    submit = SubmitField('Submit Form')

website/ws2.0/server/app/contact/__init__.py
from flask import Blueprint

contact = Blueprint('contact', __name__)

from . import views

website/ws2.0/server/app/contact/views.py
# from scurdex.app.auth.forms import ContactForm
from flask import render_template, make_response, current_app, flash, redirect, url_for, request
from flask_mail import Message
from flask_moment import Moment
from ..email import send_email
from config import config
import os
from .forms import ContactForm

from . import contact

@contact.route('/form', methods=['GET'])
def contact_us():
  template = render_template('contact/contact.html')
  response = make_response(template)
  response.headers['Cache-Control'] = 'public, max-age=300, s-maxage=600'
  return response

@contact.route('/message', methods=['GET', 'POST'])
def send_message():  
  # form = ContactForm()
  fName = request.form['fName'], lName = request.form['lName'], eAddress = request.form['eAddress'], subject=request.form['subject'], message=request.form['message']
  destination = os.environ.get('SCURDEX_ADMIN', 'scurdex@protonmail.com')
  if destination:
    send_email(destination, subject, 'contact/contact_us_email', fName=fName, lName=lName, eAddress=eAddress, subject=subject, message=message) 
    flash('Your Message Has Been Sent')
  else:
    flash('Your Message Was Not Delivered To Support Team, Please, Try Again Later')
    return redirect(url_for('contact.contact_us'))
  template = render_template('contact/email_message.html',fName=fName, lName=lName, eAddress=eAddress, subject=subject, message=message)
  response = make_response(template)
  response.headers['Cache-Control'] = 'public, max-age=300, s-maxage=600'
  return response

website/ws2.0/server/app/templates/contact/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Wallet for Crypto Trading, Investment Management & Financial Inclusion </title>
	<meta charset="UTF-8">
	<meta name="description" content="Security and Cyptocurrency Decentalized Exchange">
	<meta name="keywords" content="decentralized exchange, cryptocurrency trading, defi, private security trading, private security token offering, microinvestment, microfinance, microcredit, financial inclusion, microinsurance, micropension, startup capital">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}"/> 

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/themify-icons.css') }}"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.css') }}"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	<script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-7D2PXXE702');
    </script>

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section clearfix">
		<div class="container-fluid">
			<a href="{{ url_for('home.index') }}" class="site-logo">
				<img src="{{ url_for('static', filename='img/scurdex_logo_72px.svg') }}" alt="">
			</a>
			<div class="responsive-bar"><i class="fa fa-bars"></i></div>
			<a href="" class="user"><i class="fa fa-user"></i></a>
			<a href="{{ url_for('auth.register') }}" class="site-btn">Sign Up Free</a>
			<nav class="main-menu">
				<ul class="menu-list">
					<!--<li><a href="" style="font-size: 20px">Microfinance</a></li>-->
					<!--<li><a href="" style="font-size: 20px">Token Offerings</a></li>-->
					<li><a href="https://flutterwave.com/pay/scurdex" style="font-size: 20px">Buy Cryptos</a></li>						
					<li><a href="{{ url_for('blog') }}" style="font-size: 20px">Blog</a></li>											
					<!--<li><a href="" style="font-size: 20px">Login</a></li>-->								
				</ul>
			</nav>
		</div>
	</header>
	<!-- Header section end -->



	<!-- Page info section -->
	<section class="page-info-section">
		<div class="container">
		    <br>
			<h2 style="color:white;">You Can Say It All</h2>
			<div class="site-beradcamb">
				<a href="{{ url_for('home.index') }}" style="color:white; font-size: 20px">Home</a>
				<span><i class="fa fa-angle-right" style="font-size: 30px"></i> Contact Us </span>
			</div>
		</div>
	</section>
	<!-- Page info end -->



	<!-- Contact section -->
	<section class="contact-page spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
					<form class="contact-form" action="{{ url_for('contact.send_message') }}" method="POST" >
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<input class="check-form" type="text" id="fName" name="fName" placeholder="First Name*:">
									<span><i class="ti-check"></i></span>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<input class="check-form" type="text" id="lName" name="lName" placeholder="Last Name*:">
									<span><i class="ti-check"></i></span>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<input class="check-form" type="text" id="eAddress"name="eAddress" placeholder="Email Adress*:">
									<span><i class="ti-check"></i></span>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<input class="check-form" type="text" id="pNumber" name="pNumber" placeholder="Phone Number*:">
									<span><i class="ti-check"></i></span>
								</div>
							</div>
							<div class="col-md-12">
							    <div class="form-group">
									<input class="check-form" type="text" id="subject" name="subject" placeholder="Enter Your Message Subject Here*:">
									<span><i class="ti-check"></i></span>
								</div>
								<div class="form-group">
									<textarea placeholder="Tell us about your question!"></textarea>
								</div>
								<h5 class="mb-3">Way to Contacts<span>*</span>:</h5>
								<div class="contact-type">
								    <label class="ct-label">Email
										<input type="radio" id="emailradio" value="EmailRadio" name="radio">
										 <span class="checkmark"></span>
									</label>
									<label class="ct-label">Phone
										<input type="radio" id="phoneradio" value="PhoneRadio" name="radio">
										 <span class="checkmark"></span>
									</label>									
									<label class="ct-label">Other
										<input type="radio" id="otherradio" value="OtherRadio" name="radio">
										 <span class="checkmark"></span>
									</label>
								</div>

								<button class="site-btn sb-gradients mt-4">Submit form</button>
							</div>
						</div>
					</form>
				</div>
				<div class="col-lg-5 mt-5 mt-lg-0">
					<div class="map" id="map-canvas">					
						<div class="map">
						    <!--<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3963.761219784648!2d3.3644466508120012!3d6.551801924626959!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103b8d90d838fec7%3A0xfe3539bb6b791233!2s223%20Ikorodu%20Rd%2C%20Ilupeju%20102215%2C%20Lagos!5e0!3m2!1sen!2sng!4v1628383091140!5m2!1sen!2sng" -->
							<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3452.962201753805!2d-89.95174714898486!3d30.06661792439016!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x889e01620a207ad3%3A0x6b76ce39ec4f2f9a!2s14023%20Curran%20Rd%2C%20New%20Orleans%2C%20LA%2070128%2C%20USA!5e0!3m2!1sen!2sng!4v1628380988819!5m2!1sen!2sng"
							  width="510" 
							  height="400" 
							  style="border:0;" 
							  allowfullscreen="" 
							  loading="lazy">
							</iframe>
						</div>								
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Contact section end -->


	<!-- Newsletter section -->
	<section class="newsletter-section gradient-bg">
		<div class="container text-white">
			<div class="row">
				<div class="col-lg-7 newsletter-text">
					<h2>Subscribe to our Newsletter</h2>
					<p>Sign up for our weekly industry updates, insider perspectives and in-depth market analysis.</p>
				</div>
				<div class="col-lg-5 col-md-8 offset-lg-0 offset-md-2">
					<form class="newsletter-form">
						<input type="text" placeholder="Enter your email">
						<button>Get Started</button>
					</form>
				</div>
			</div>
		</div>
	</section>
	<!-- Newsletter section end -->

	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">
			<div class="row spad">
				<div class="col-md-6 col-lg-3 footer-widget">
					<img src="{{ url_for('static', filename='img/scurdex_logo_72px.svg') }}" class="mb-4" alt="">
					<p>A Fully Decentralized Exchange for 2000+ Cryptocurrencies, Foreign Exchange, Stocks and Bonds. You can also get various microfinancial services like insurance, payment, etc</p>					
				</div>
				<div class="col-md-6 col-lg-2 offset-lg-1 footer-widget">
					<h5 class="widget-title" style="color:black;">Quick Links</h5>
					<ul>
						<li><a href="#">Funding Account</a></li>
						<li><a href="#">Merchant Onboarding</a></li>
						<li><a href="#">Payment Methods</a></li>
						<li><a href="#">Trading Currencies</a></li>
						<li><a href="#">Wallet User Guides</a></li>
					</ul>
				</div>
				<div class="col-md-6 col-lg-2 offset-lg-1 footer-widget">
					<h5 class="widget-title" style="color:black;">Resources</h5>
					<ul>
						<li><a href="#">Stock & Bond Markets</a></li>						
						<li><a href="{{ url_for('static', filename='pdf/scurdexwhitepaper.pdf') }}">Scurdex White Paper</a></li>
						<li><a href="{{ url_for('static', filename='pdf/scurdexpd.pdf') }}">Scurdex Pitch Deck</a></li>
						<li><a href="{{ url_for('static', filename='pdf/regulation.pdf') }}">Crypto Regulations</a></li>
						<li><a href="{{ url_for('static', filename='pdf/fintech.pdf') }}">FinTech Outlook</a></li>
					</ul>
				</div>
				<div class="col-md-6 col-lg-3 footer-widget pl-lg-5 pl-3">
					<h5 id="contactus" class="widget-title" style="color:black;">Follow Us</h5>
					<div class="social">
						<a href="https://facebook.com/scurdex" class="facebook"><i class="fa fa-facebook"></i></a>						
						<!--<a href="" class="instagram"><i class="fa fa-instagram"></i></a>-->
						<a href="https://twitter.com/scur_dex" class="twitter"><i class="fa fa-twitter"></i></a>
						<a href="https://t.me/scurdex" class="twitter"><i class="fa fa-telegram"></i></a>
						<a href="https://www.youtube.com/channel/UCjkptlxY0ANhnKW0BYXmQrQ" class="twitter"><i class="fa fa-youtube"></i></a>
					</div>
				</div>
			</div>
			<div class="footer-bottom">
				<div class="row">
					<div class="col-lg-4 store-links text-center text-lg-left pb-3 pb-lg-0">
						<a href="https://play.google.com/store/apps/details?id=com.nichie.curdex"><img src="img/playstore.png" alt=""  class="mr-3"></a>
						<!--<a href=""><img src="img/appstore.png" alt=""></a> -->						
					</div>
					<div class="col-lg-8 text-center text-lg-right">
						<ul class="footer-nav">
							<!--<li><a href="">DPA</a></li>-->
							<li><a href="{{ url_for('static', filename='pdf/tac.pdf') }}">Terms of Service</a></li>
							<li><a href="{{ url_for('static', filename='pdf/privacy.pdf') }}">Privacy Policy </a></li>
							<li><a href="mailto:scurdex@protonmail.com?cc=support@scurdex.com, &bcc=samson.amosu@scurdex.com&subject=Scurdex Enquiry&body=Dear Scurdex Team,">Send Us EMail</a></li>
							<!--<li><a href="">+1(504)503-3360</a></li>
							<li><a href="">+234(708)999-7878</a></li>-->
						</ul>
						<span>
							<a href="https://www.scurdex.com" target="_blank" style="color:black;">Copyright &copy;<script>document.write(new Date().getFullYear());</script> Scurdex is a Product of Nichie Systems</a>							
						</span>
					</div>
				</div>
			</div>
		</div>
	</footer>

	<!--====== Javascripts & Jquery ======-->
	<script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/owl.carousel.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>
	<script type="application/javascript" src="{{ url_for('static', filename='js/buycrypto.js') }}"></script>
	<script>
		function initFreshChat() {
		  window.fcWidget.init({			
			token: "7fac6839-9181-4846-a4ca-6f7550cb9f39",
			host: "https://wchat.freshchat.com"
		  });
		  
		  // To set unique user id in your system when it is available
		  window.fcWidget.setExternalId("");

		  // To set user name
		  window.fcWidget.user.setFirstName("");

		  // To set user email
		  window.fcWidget.user.setEmail("");

		  // To set user properties
		  window.fcWidget.user.setProperties({
		    plan: "Pro",                  // meta property 1
		    status: "Active"              // meta property 2
		  });
		}
		function initialize(i,t){var e;i.getElementById(t)?initFreshChat():((e=i.createElement("script")).id=t,e.async=!0,e.src="https://wchat.freshchat.com/js/widget.js",e.onload=initFreshChat,i.head.appendChild(e))}function initiateCall(){initialize(document,"Freshdesk Messaging-js-sdk")}window.addEventListener?window.addEventListener("load",initiateCall,!1):window.attachEvent("load",initiateCall,!1);
	</script>
</body>
</html>

website/ws2.0/server/app/templates/contact/contact_us_email.html
<p>Dear Admin,</p>
<p>You just got a message from {{ fName }}!</p>
<p>Here are the details of the message: </p>
<p>Full Name of Sender: {{ fName }} {{ lName}} </p>
<p>Email: {{ eAddress }} </p>
<p>Telephone: {{ pNumber }} </p>
<p>Subject: {{ subject }} </p>
<p>Message: {{ message }} </p>
<p><small>Note: replies to this email address are not monitored.</small></p>

website/ws2.0/server/app/templates/contact/email_message.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Wallet for Crypto Trading, Investment Management & Financial Inclusion </title>
	<meta charset="UTF-8">
	<meta name="description" content="Security and Cyptocurrency Decentalized Exchange">
	<meta name="keywords" content="decentralized exchange, cryptocurrency trading, defi, private security trading, private security token offering, microinvestment, microfinance, financial inclusion, microinsurance, micropension, startup capital">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon"/> 
	<link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon"/>

	<!-- Google Fonts -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato"/>

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/themify-icons.css') }}"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.css') }}"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>

    <script src="https://cdn.jsdelivr.net/npm/@ramp-network/ramp-instant-sdk@2.3.0/dist/ramp-instant-sdk.umd.js" integrity="sha256-heFylj/fcCZffQpQuqUmrk1e08vdaGcpw0w9mWGnbz4=" crossorigin="anonymous"></script>
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

	<script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-7D2PXXE702');
    </script>

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section clearfix">
		<div class="container-fluid">
			<!--<a href="index.html" class="site-logo">-->
			<a href="{{ url_for('home.index') }}" class="site-logo">
				<img src="img/scurdex_logo_72px.svg" alt="">
			</a>
			<div class="responsive-bar"><i class="fa fa-bars"></i></div>
			<a href="" class="user"><i class="fa fa-user"></i></a>
			<a href="{{ url_for('auth.register') }}" class="site-btn">Sign Up Free</a>
			<nav class="main-menu">
				<ul class="menu-list">
					<!--<li><a href="" style="font-size: 20px">Microfinance</a></li>-->
					<!--<li><a href="" style="font-size: 20px">Token Offerings</a></li>-->
					<li><a href="https://flutterwave.com/pay/scurdex" style="font-size: 20px">Buy Cryptos</a></li>						
					<li><a href="{{ url_for('blog') }}" style="font-size: 20px">Blog</a></li>											
					<!--<li><a href="" style="font-size: 20px">Login</a></li>-->								
				</ul>
			</nav>
		</div>
	</header>
	<!-- Header section end -->
    
    <!-- Hero section -->
	<section class="hero-section spad gradient-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-5 hero-text">
				    <!--<h3 style="color:white"><small>This website is under development </small></h3>
					<h2>Welcome to <span>Scurdex</span> </h2>
                    -->
					<p style="color:black; font-size: 30px">Dear {{ fName }} {{ lName }}</p>
					<h3 style="color:black">Thank You!!!</h3>					
					<a style="color:black; font-size: 20px">Your message has been successfully sent to </a>
                    <a style="color:blue; font-size: 20px">{{ eAddress }} </a>
                    <a style="color:black; font-size: 20px">A member of our support team will contact you soon with an appropriate feedback. </a>
					<br>
					<br>
					<a style="color:black; font-size: 30px">Yours sincerely</a><br>
                    <a style="color:black; font-size: 30px">Support Team</a>
					
				</div>
				<div class="col-md-6">
					<!--<img src="img/laptop.png" class="laptop-image" alt=""> -->
					<!--<div style="height:560px; background-color: #FFFFFF; overflow:hidden; box-sizing: border-box; border: 1px solid #56667F; border-radius: 4px; text-align: right; line-height:14px; font-size: 12px; font-feature-settings: normal; text-size-adjust: 100%; box-shadow: inset 0 -20px 0 0 #56667F;padding:1px;padding: 0px; margin: 0px; width: 100%;"><div style="height:540px; padding:0px; margin:0px; width: 100%;"><iframe src="https://widget.coinlib.io/widget?type=chart&theme=light&coin_id=145&pref_coin_id=1505" width="100%" height="536px" scrolling="auto" marginwidth="0" marginheight="0" frameborder="0" border="0" style="border:0;margin:0;padding:0;line-height:14px;"></iframe></div><div style="color: #FFFFFF; line-height: 14px; font-weight: 400; font-size: 11px; box-sizing: border-box; padding: 2px 6px; width: 100%; font-family: Verdana, Tahoma, Arial, sans-serif;"><a href="https://coinlib.io" target="_blank" style="font-weight: 500; color: #FFFFFF; text-decoration:none; font-size:11px">Cryptocurrency Prices</a>&nbsp;by Coinlib</div></div>-->
					<!-- TradingView Widget BEGIN -->                    
                    
				</div>				
			</div>
			<br>
			<div>
				<!--<div style="height:62px; background-color: #FFFFFF; overflow:hidden; box-sizing: border-box; border: 1px solid #56667F; border-radius: 4px; text-align: right; line-height:14px; block-size:62px; font-size: 12px; font-feature-settings: normal; text-size-adjust: 100%; box-shadow: inset 0 -20px 0 0 #56667F;padding:1px;padding: 0px; margin: 0px; width: 100%;"><div style="height:40px; padding:0px; margin:0px; width: 100%;"><iframe src="https://widget.coinlib.io/widget?type=horizontal_v2&theme=light&pref_coin_id=1505&invert_hover=yes" width="100%" height="36px" scrolling="auto" marginwidth="0" marginheight="0" frameborder="0" border="0" style="border:0;margin:0;padding:0;"></iframe></div><div style="color: #FFFFFF; line-height: 14px; font-weight: 400; font-size: 11px; box-sizing: border-box; padding: 2px 6px; width: 100%; font-family: Verdana, Tahoma, Arial, sans-serif;"><a href="https://coinlib.io" target="_blank" style="font-weight: 500; color: #FFFFFF; text-decoration:none; font-size:11px">Cryptocurrency Prices</a>&nbsp;by Coinlib</div></div> -->
			</div>
		</div>
	</section>
	<!-- Hero section end -->




	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">
			<div class="row spad">
				<div class="col-md-6 col-lg-3 footer-widget">
					<img src="{{ url_for('static', filename='img/scurdex_logo_72px.svg') }}" class="mb-4" alt="">
					<p>A Fully Decentralized Exchange for 2000+ Cryptocurrencies, Foreign Exchange, Stocks and Bonds. You can also get various microfinancial services like insurance, payment, etc</p>					
				</div>
				<div class="col-md-6 col-lg-2 offset-lg-1 footer-widget">
					<h5 class="widget-title" style="color:black;">Quick Links</h5>
					<ul>
						<li><a href="#">Funding Account</a></li>
						<li><a href="#">Merchant Onboarding</a></li>
						<li><a href="#">Payment Methods</a></li>
						<li><a href="#">Trading Currencies</a></li>
						<li><a href="#">Wallet User Guides</a></li>
					</ul>
				</div>
				<div class="col-md-6 col-lg-2 offset-lg-1 footer-widget">
					<h5 class="widget-title" style="color:black;">Resources</h5>
					<ul>
						<li><a href="#">Stock & Bond Markets</a></li>						
						<li><a href="{{ url_for('static', filename='pdf/scurdexwhitepaper.pdf') }}">Scurdex White Paper</a></li>
						<li><a href="{{ url_for('static', filename='pdf/scurdexpd.pdf') }}">Scurdex Pitch Deck</a></li>
						<li><a href="{{ url_for('static', filename='pdf/regulation.pdf') }}">Crypto Regulations</a></li>
						<li><a href="{{ url_for('static', filename='pdf/fintech.pdf') }}">FinTech Outlook</a></li>
					</ul>
				</div>
				<div class="col-md-6 col-lg-3 footer-widget pl-lg-5 pl-3">
					<h5 id="contactus" class="widget-title" style="color:black;">Follow Us</h5>
					<div class="social">
						<a href="https://facebook.com/scurdex" class="facebook"><i class="fa fa-facebook"></i></a>						
						<!--<a href="" class="instagram"><i class="fa fa-instagram"></i></a>-->
						<a href="https://twitter.com/scur_dex" class="twitter"><i class="fa fa-twitter"></i></a>
						<a href="https://t.me/scurdex" class="twitter"><i class="fa fa-telegram"></i></a>
						<a href="https://www.youtube.com/channel/UCjkptlxY0ANhnKW0BYXmQrQ" class="twitter"><i class="fa fa-youtube"></i></a>
					</div>
				</div>
			</div>
			<div class="footer-bottom">
				<div class="row">
					<div class="col-lg-4 store-links text-center text-lg-left pb-3 pb-lg-0">
						<a href="https://play.google.com/store/apps/details?id=com.nichie.curdex"><img src="img/playstore.png" alt=""  class="mr-3"></a>
						<!--<a href=""><img src="img/appstore.png" alt=""></a> -->						
					</div>
					<div class="col-lg-8 text-center text-lg-right">
						<ul class="footer-nav">
							<!--<li><a href="">DPA</a></li>-->
							<li><a href="{{ url_for('static', filename='pdf/tac.pdf') }}">Terms of Service</a></li>
							<li><a href="{{ url_for('static', filename='pdf/privacy.pdf') }}">Privacy Policy </a></li>
							<li><a href="mailto:scurdex@protonmail.com?cc=support@scurdex.com, &bcc=samson.amosu@scurdex.com&subject=Scurdex Enquiry&body=Dear Scurdex Team,">Send Us EMail</a></li>
							<!--<li><a href="">+1(504)503-3360</a></li>
							<li><a href="">+234(708)999-7878</a></li>-->
						</ul>
						<span>
							<a href="https://www.scurdex.com" target="_blank" style="color:black;">Copyright &copy;<script>document.write(new Date().getFullYear());</script> Scurdex is a Product of Nichie Systems</a>							
						</span>
					</div>
				</div>
			</div>
		</div>
	</footer>

	<!--====== Javascripts & Jquery ======-->
	<script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/owl.carousel.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>
	<script type="application/javascript" src="{{ url_for('static', filename='js/buycrypto.js') }}"></script>
	<script>
		function initFreshChat() {
		  window.fcWidget.init({			
			token: "7fac6839-9181-4846-a4ca-6f7550cb9f39",
			host: "https://wchat.freshchat.com"
		  });
		  
		  // To set unique user id in your system when it is available
		  window.fcWidget.setExternalId("");

		  // To set user name
		  window.fcWidget.user.setFirstName("");

		  // To set user email
		  window.fcWidget.user.setEmail("");

		  // To set user properties
		  window.fcWidget.user.setProperties({
		    plan: "Pro",                  // meta property 1
		    status: "Active"              // meta property 2
		  });
		}
		function initialize(i,t){var e;i.getElementById(t)?initFreshChat():((e=i.createElement("script")).id=t,e.async=!0,e.src="https://wchat.freshchat.com/js/widget.js",e.onload=initFreshChat,i.head.appendChild(e))}function initiateCall(){initialize(document,"Freshdesk Messaging-js-sdk")}window.addEventListener?window.addEventListener("load",initiateCall,!1):window.attachEvent("load",initiateCall,!1);
	</script>
</body>
</html>